### ISSUE TITLE
Can't find dsi

### ISSUE THREAD

**Issue by udaykamal20** [neuromorphicsystems/IEBCS#1]
Hi,
Thanks for sharing your work. While trying to install the environment, I came across this error:

"ERROR: Could not find a version that satisfies the requirement dsi (from versions: none)
ERROR: No matching distribution found for dsi"

I tried to look for this dsi library but it seems to be non-existent. Am I missing something here? I think this library is crucial to instantiate the sensor since I tried to follow the next steps without this one but did not succeed. 

Any help/lead would be greatly appreciated!

**Comment by joubertdamien** [comment]
Hello @udday2014 , 
You need to compile and install the Python bindings. 
This [script](https://github.com/neuromorphicsystems/IEBCS/blob/main/cpp/compile_test.sh) should do the job, let me know if anything goes wrong, I'll be pleased to help.  
Cheers

**Comment by udaykamal20** [comment]
Sorry for my delayed response and many thanks for your prompt response, it worked without any further issues!

**Comment by joubertdamien** [comment]
Ok good then. Can I let you close the issue ? @udaykamal20

**Comment by udaykamal20** [comment]
Yes, sure. Please go ahead and do so. Thanks again!
