### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by sofiacatalan** [neuromorphicsystems/IEBCS#2]
Hello, 

Can you clarify under what software license this code can be used with? I'd like to use this as a simulation engine for generating events. 

Thanks!

**Comment by joubertdamien** [comment]
Hello @sofiacatalan , 
Apologies for the late answer, and for forgetting it. 
We are in [GPL3](https://choosealicense.com/licenses/gpl-3.0/)

**Comment by sofiacatalan** [comment]
Thanks for the response!
