### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by sopje** [neuromorphicsystems/IEBCS#4]
Hi, 

I have installed everything to run your code using conda with the steps described. I am running on Ubuntu 22.04.2. I tried the example of Video -> events using data>examples>get_video_youtube.py and then example_video_to_events.py. When I try to download from Youtube, I run into problems (pytube.exceptions.RegexMatchError), this is fixed by updating the package (see:https://stackoverflow.com/questions/68945080/pytube-exceptions-regexmatcherror-get-throttling-function-name-could-not-find). 
Now, when I try to convert the just downloaded video to event-based data, I get the following error:

ImportError: /home/s4583639/anaconda3/envs/testSimu/lib/python3.8/site-packages/loris_extension.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

When I tried to install everything without conda (using venv), I get the same error:
ImportError: /home/s4583639/Documents/Thesis Code/Simulation Event Based/IEBCS-main/.venv/lib/python3.9/site-packages/loris_extension.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

Hope you can help me with this,

Kind Regards,

Sophie

**Comment by joubertdamien** [comment]
Hello Sophie, 
I will try to replicate your issue. 
In the meantime, could you please confirm that you have [compiled](https://github.com/neuromorphicsystems/IEBCS/blob/main/cpp/compile_test.sh) after activating the virtual python environment ? 
From your second issue, it seems that you cannot import loris. How did you configure your .venv ?

**Comment by sopje** [comment]
Hi,

Thanks for your answer. I tried to replicate creating the venv again. I am now stuck at downloading the aedat==1.2.1 package. I remember I did compile after activating the venv. It seems I cannot get it to work again with venv. 

Kind Regards,
Sophie

**Comment by joubertdamien** [comment]
Hello,

Sorry again for this: my install documentation was bad, and  the install settings not working with Ubuntu22. Conda is also coming with its own g++ compiler, and the symbol errors you had are likely to come from packages not compiled with the same compiler. 
Now it should be working in Ubuntu22/Python3.8.

Let me know if you want to to test with newer Python version. Using [Distutils](https://docs.python.org/3/library/distutils.html) is depreciated since Python 3.12, I will update it anyway. 

Cheers
Damien

**Comment by joubertdamien** [comment]
(you can follow the changes in https://github.com/joubertdamien/IEBCS/tree/tests/ubuntu22, likely to be merged soon

**Comment by joubertdamien** [comment]
Hello @sopje , the PR was merged few weeks ago, did it solve your issues ?

**Comment by vschaik** [comment]
This should be fixed now after the latest merge.
