### ISSUE TITLE
Clutter events

### ISSUE THREAD

**Issue by sofiacatalan** [neuromorphicsystems/IEBCS#6]
Is there a way to turn off clutter events from being generated, such that only events from moving objects/brightness changes are included?

**Comment by joubertdamien** [comment]
Hello Sofia, Yes it is possible, you can call dsi.disableNoise() in Python. 
Let me know if it works, otherwise I will make it work. 
Cheers
Damien

**Comment by sofiacatalan** [comment]
yes that worked perfectly, thank you so much!
