### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by MariamAlz** [neuromorphicsystems/IEBCS#7]
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/mariam/anaconda3/envs/testSimu/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/mariam/IEBCS/condaenv.4_88ffs0.requirements.txt']
Pip subprocess output:
Collecting aedat==1.2.1
  Downloading aedat-1.2.1-cp38-cp38-manylinux2014_x86_64.whl (388 kB)
Collecting cycler==0.10.0
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement dsi==1.0 (from versions: none)
ERROR: No matching distribution found for dsi==1.0

failed

CondaEnvException: Pip failed

**Comment by joubertdamien** [comment]
Hello Mariam, 
Sorry, I did a mistake in rhe previous PR, you should remove line 28 in https://github.com/neuromorphicsystems/IEBCS/blob/main/simuDVSICNS.yml

**Comment by vschaik** [comment]
This should be fixed now.
